### ISSUE TITLE
Item pickups spawn when samus doesn't have the item

### ISSUE THREAD

**Issue by sunsetbear** [Scooterboot/Re-Boot-Engine#3]
If samus doesn't have missiles, and kills an enemy, it may still drop missiles (expected behavior would be energy or nothing.) Same goes for supers and PBs.

**Comment by Scooterboot** [comment]
Enemy item drop code is very WIP, so this'll probably get fixed whenever that gets rewritten.

**Comment by Scooterboot** [comment]
Item drop code has been rewritten to reflect how it functions in SM, and by extension, this issue has been fixed.
